package pages;

import driver.DriverSingleton;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;
import util.ForTheTextSearching;
import util.GenerateRandomMail;

import java.util.ArrayList;
import java.util.List;

public class StorePage extends BaseAbstractPage {
    private  static final String MYPAGE_URL = "http://automationpractice.com/index.php";

    /**
     * constructor for  fields initialization
     */
    public StorePage(){
        super(DriverSingleton.getDriver());
        PageFactory.initElements(driver, this);
    }

    @FindBy(xpath ="//div[@class=\"product-container\"]//a[@class=\"product-name\"]")
    private List<WebElement> openedItemList; // return list of opened elements
    //private WebElement firstItem = openedItemList.get(0); // get first element from the list

    @FindBy(xpath = "//h1[@itemprop='name']")
    private WebElement firstItemName;
    @FindBy(xpath = "//*[@id=\"newsletter-input\"]")
    private WebElement subscribeMailField;

    @FindBy(xpath = "//*[@id=\"columns\"]/p")
    private WebElement messageAfterSubscribing;

    @FindBy(xpath = "//*[@class='login']")
    private WebElement signInButton;

    @FindBy(xpath = "//*[@id=\"search_query_top\"]")
    private WebElement searchField;

    @FindBy(xpath = "//ul[@class=\"product_list grid row\"]//a[@class=\"product-name\"]")
    //Get List with all founded web-elements
    private List<WebElement> searchResults;

    @FindBy(css = "a[title='View my customer account'] span")
    private WebElement accountName;

    public StorePage openPage(){
        driver.get(MYPAGE_URL);
        return this;
    }

    public ProductPage openFirstItem(){
        WebElement firstItem = openedItemList.get(0);
        firstItem.click();
        return new ProductPage();
    }

    public String subscribeSucessfully(){
        //Send email generated by my own mail generator class
        subscribeMailField.sendKeys(GenerateRandomMail.getSaltString(), Keys.ENTER);
        return messageAfterSubscribing.getText();
    }

    public String subscribeWithInvalidData(){
        subscribeMailField.sendKeys("test", Keys.ENTER);
        return messageAfterSubscribing.getText();
    }

    public SignInPage openSignInPage(){
        signInButton.click();
        //return Sing in page on clicking the SignIn button
        return new SignInPage();
    }

    public  boolean searchItem(String data){
        //use config with a word that we want to search by
        searchField.sendKeys(data, Keys.ENTER);
        List<String> blouseResultsForGettingTitle = new ArrayList();

        //Create list with titles
        for (WebElement element : searchResults) {
            blouseResultsForGettingTitle.add(element.getAttribute("Title"));
        }
        //Stream version
        //blouseResultsForGettingTitle= searchResults.stream().map(webElement -> webElement.getAttribute("Title")).collect(Collectors.toList());
        return ForTheTextSearching.StreamForTheText(blouseResultsForGettingTitle, data);
    }

    public String getAccountName(){
        return accountName.getText();
    }
}
